### ISSUE TITLE
Integrate CI with Github

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#89]
one person from each platform should work together to decide on CDG's CI policies and to set up Github integration.

**Comment by festrs** [comment]
As we spoke in Slack I'm attacking a code of .travis.yml file for iOS that works with cocoapods dependency manager. Please, if you guys can create a free account and test this. Follow the website https://docs.travis-ci.com/user/languages/objective-c/ for more!

`language: objective-c

osx_image: xcode8.3

script:
  - xcodebuild -version
  - xcodebuild -workspace ProjectName.xcworkspace -scheme 'ProjectScheme' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" test`

**Comment by abbeyjackson** [comment]
@festrs, @renatomcamilio is CodeDoesGood's technical contact. He should see this message but if he doesn't message him on Slack and he will help you out.

Renato, see above :)

Also I'd like to see @gopesh-sharma @sinha-abhishek participating. Have you guys talked with Felipe about your platforms? Is Travis going to be appropriately set up for each?

**Comment by sinha-abhishek** [comment]
Setting travis for android development as well. Will update the timelines

**Comment by renatomcamilio** [comment]
Just confirming: what's needed from me on this one? Just create a hello world iOS app with cocoapods and test against travis? Do we have a test app to simplify the process? 
ty!

**Comment by festrs** [comment]
I can do this, and you can check if everything is in the place! That's sounds good?

**Comment by renatomcamilio** [comment]
That'd be perfect. 👍

**Comment by festrs** [comment]
Check out this project https://github.com/festrs/CI-Template-CDG 
I don't know how to include this template in the CDG GIT. Nevertheless, there are some configs that are needed on the project to, I'll write some instructions on the readme of this project later.

**Comment by abbeyjackson** [comment]
@festrs @sinha-abhishek @gopesh-sharma Can you guys use the template projects on CDG's github to test this stuff out? You can push non important commits to check the CI is working. The Android template is just a readme and the Web template is an empty repo but you can add CI and just push whatever you want to check that the CI is hooked up.

@swiftcode is going to be looking into integrating Travis into slack
https://github.com/CodeDoesGood/org/issues/134

Related Repos:
[](https://github.com/CodeDoesGood/iOS-Template)
[](https://github.com/CodeDoesGood/Android-Template)
[](https://github.com/CodeDoesGood/Web-Template)

Please coordinate with @GrfxGuru (Peter Witham) to get the credentials for the shared volunteers email address so that you can use it to create CDG based accounts.

**Comment by abbeyjackson** [comment]
I just stumbled on this link, did you know that there is already a Travis
integration for Github?
https://github.com/integrations/feature/continuous-integration

**Comment by swiftcode** [comment]
I thought there might be.  Will be able to work on the integration this evening.

**Comment by festrs** [comment]
@abbeyjackson I'll do this on Monday that's ok? Can I push PR to the iOS template with travis.yml?

**Comment by swiftcode** [comment]
I setup the integration with dev-ios and dev-android.  What is the process going to be to test this?

**Comment by abbeyjackson** [comment]
@festrs you can use ios-template and android-template repos to test. Push whatever you want :)

**Comment by festrs** [comment]
I made a PR yesterday on iOS-Template with the travis config for iOS

**Comment by vitalii-tym** [comment]
I'm trying to [integrate Danger](https://github.com/CodeDoesGood/business/issues/109), but found that current Travis integration doesn't function well. At least It fails in my fork before getting to any Danger-related stuff.

I'm trying to figure out what has happened since the time @festrs had it [successfully running](https://github.com/festrs/CI-Template-CDG) back on May 4 (see previous comments).

Issues I see at the moment are:
1. MINOR: Travis is not turned on for iOS-Template at CodeDoesGood org. Someone with admin rights for the org has to turn it on (just go to https://travis-ci.org/profile/CodeDoesGood and turn the light on for the iOS-Template repo)
2. MINOR: The "bundle install" command repeats twice. First it is triggered from .travis.yml and then later it is again triggered by Travis itself (because Travis automatically runs Bundler if it detects a Gemfile is present)
3. CRITICAL: Command "bundle exec pod install" fails. The most interesting lines are:
```
NameError - uninitialized constant CocoaPodsKeys::PreInstaller::Informative
/Users/travis/build/vitalii-tym/iOS-Template/vendor/bundle/ruby/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Users/travis/build/vitalii-tym/iOS-Template/vendor/bundle/ruby/2.3.0/gems/cocoapods-keys-2.0.0/lib/preinstaller.rb:46:in `block in setup'
/Users/travis/build/vitalii-tym/iOS-Template/vendor/bundle/ruby/2.3.0/gems/cocoapods-keys-2.0.0/lib/preinstaller.rb:43:in `each'
```
(Full log is available here: https://travis-ci.org/vitalii-tym/iOS-Template)

I suspect there might be some mismatches either in supported Ruby versions or wrong path somewhere.
I will continue investigation later as soon as I have time. But if someone has any idea what could go wrong - let me know.

**Comment by vitalii-tym** [comment]
Found that the build process runs fine after commenting out this code from Podfile: 
```
#  plugin 'cocoapods-keys', {
#    :project => "CodeDoesGood-iOSTemplate",
#    :keys => [
#    "NetworkAPIToken"
#  ]}
```
I'm out of my time now. Will return to this issue later.

**Comment by festrs** [comment]
This error is because this no such key in the Travis configuration, someone with access needs to include the key on Travis config. Check this tutorial for more information https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by abbeyjackson** [comment]
Who has access? I don't even know how Travis is set up as I wasn't
involved. If you look at the github issues you should be able to find who
set it up and they may know. Once you find that out can you please give
this information to me via a private message on slack so that I can record
it in case we need it in the future. Thanks!

**Comment by gabrielPeart** [comment]
I will have a look at it!

**Comment by vitalii-tym** [comment]
@gabrielPeart, no worries. It's all up now.
I was surprised, but somehow I had access to add env variables to the org's Travis account for the iOS-Template project. So, with [these settings](https://travis-ci.org/CodeDoesGood/iOS-Template/settings) Travis, cocoapods-keys, and Danger are running fine now:

**Comment by gabrielPeart** [comment]
@vitalii-tym great work! Thank you very much!

**Comment by festrs** [comment]
@vitalii-tym Good job! Thanks for all!
